project_id = "xrwvaelhmibhslmfvxrs"

[auth]
site_url = "https://trade-stryke.vercel.app"
additional_redirect_urls = ["https://trade-stryke.vercel.app", "https://trade-stryke.vercel.app/dashboard", "http://localhost:5173", "http://localhost:5173/dashboard"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
